# Generated by Django 4.2 on 2023-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_number_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='type',
            field=models.CharField(choices=[('I', 'incoming'), ('O', 'outgoing')], max_length=1),
        ),
    ]
