# Generated by Django 4.2 on 2023-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accounthistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='balance_after_transfer',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
