# Generated by Django 4.2 on 2023-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accounthistory_balance_after_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='amount',
            field=models.FloatField(),
        ),
    ]
