# Generated by Django 4.2 on 2023-04-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_accounthistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
